apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: user-app
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/Tabeebashraf7/argocd-multiapp-setup.git
    targetRevision: master
    path: k8s/user-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
