apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: order-app

  template:
    metadata:
      labels:
        app: order-app

    spec:
      containers:
      - name: order-container

        image: syedtabibashraf/order-service:v1

        ports:
        - containerPort: 80020
